// import Navbar from '@/components/Navbar';
// import Footer from '@/components/Footer';
// import { AnimatePresence } from 'framer-motion';
import { Inter } from 'next/font/google';
import './globals.css';
// import Navbar from '@/components/Navbar';
// import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import NavbarContainer from '@/components/NavbarContainer';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <div className=''>
          {/* <Header />
          <div className='flex-grow mt-20'>{children}</div>
          <Footer /> */}
          <NavbarContainer />
          <div className=''>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
